### ISSUE TITLE
Remove _content.scss styles

### ISSUE THREAD

**Issue by anyssa** [HasteDesign/Haste-Starter#27]
These content styles are not applicable to the majority of projects, so the file must either come empty or not exist at all by default.

**Comment by allysonsouza** [comment]
The empty file only makes sense if we want to dictate how things should be named, or which files should exist, I don't think we'll go this way with Haste Starter, so it's probably better to just remove it.

**Comment by anyssa** [comment]
When removing files remember to also remove it's references, like the reference for this file at main.scss. 

Also, we will maintian this file as a reminder to style the content of the posts.
