### ISSUE TITLE
Base styles for some popular plugins

### ISSUE THREAD

**Issue by anyssa** [HasteDesign/Haste-Starter#29]
As @allysonsouza suggested once, provide basic styles and adjustments for some of the plugins we always use. We could define a separated stylesheet for each plugin in src/scss/vendors, and then these sheets could be removed or added depending if the plugin is being use.

IMO, this could cause bigger CSS files, with unecessary styles being loaded. We have to come up with an approach to remove unused styles. Or we could simply save the styles in another place, a gist maybe?

Some suggestions:

- Contact Form 7: styles for form fields (extend Bootstrap's) and validation messages;
- Elementor: line heights of the headings (it always sets it to zero, for no reason), maybe buttons extending the theme button styles;
- WooCommerce: Mini cart, tables, my account , login;
- Registrations for  WooCommerce;

**Comment by allysonsouza** [comment]
It's fine if the files are in a `src/scss/vendors` folder and included only if needed by each project, so this will not lead to a unnecessary big compiled css.

**Comment by GabrielHenriqueRS** [comment]
Analyzing the most recent projects, I filtered some stylesheets. Can you comment on what you think?

**Comment by GabrielHenriqueRS** [comment]
Analyzing the most recent projects, I filtered some stylesheets. Can you comment on what you think?

_WooCommerce_
`// Mini cart
.woocommerce-mini-cart__buttons {
	a {
		@include btn;
			&:nth-of-type(1) {
				@include button-variant($white, $white);
			}
			&:nth-of-type(2) {
				@include button-variant($dark, $dark);
			}
		}
	}
}
// My Account
body {
	&.woocommerce-account {
		.woocommerce {
			display: grid;
			grid-template-columns: 1fr 1fr 2fr;
			grid-gap: 45px;
			@include media-breakpoint-down(md) {
				display: flex;
				flex-direction: column-reverse;
			}
		}
	}
}
.woocommerce-MyAccount-navigation {
	grid-column: 1;
	ul {
		padding: 0;
		margin: 0;
		list-style: none;
		display: grid;
	}
	li {
		border: 1px solid $dark;
		margin-bottom: -4px;
		background: $white;
	}
	a {
		padding: 1em 2em;
	    display: block;
		color: $dark;
	}
}
.woocommerce-MyAccount-content {
	grid-column: 2 / span 2;
}
// Login
.woocommerce-notices-wrapper{
	grid-column: 1 / span 3;
}
#customer_login {
	grid-column: 1 / span 3;
	grid-template-columns: repeat(2, 50%);
	grid-gap: 45px;
	@include media-breakpoint-up(md) {
		display: grid;
	}
	.col-1 {
		max-width: 100%;
		@include media-breakpoint-up(md) {
			max-width: 75%;
		}
	}
	.login {
		:nth-of-type(3) {
			flex-direction: row;
			justify-content: space-between;
		}
	}
	.col-2 {
		max-width: 75%;
		@include media-breakpoint-down(md) {
			margin-top: 50px;
			max-width: 100%;
		}
		.woocommerce-password-strength {
			padding: 10px;
			transition: $transition-soft;
			color: $black;
			font-weight: $font-weight-bold;
			&.short,
			&.bad {
				background-color: $danger;
			}
			&.good {
				background-color: $warning;
			}
			&.strong {
				background-color: $success;
			}
		}
		.button {
			align-self: flex-end;
		}
	}
	.woocommerce-form {
		margin-top: 70px;
	}
	.woocommerce-Input--text {
		background-color: $white;
	}
	.form-row {
		flex-direction: column;
		label {
			font-size: $font-size-base;
		}
		span {
			font-size: $font-size-base;
			color: $dark;
		}
	}
	.button {
		width: 250px;
		@include media-breakpoint-down(md) {
		    margin: 15px 0;
			width: 100%;
		}
		@extend .btn, .btn-dark;
	}
	.lost_password {
		text-align: right;
		@include media-breakpoint-down(md) {
		    margin-left: -10px;
		}
		a {
			width: 250px;
			margin-right: -5px;
			@include media-breakpoint-down(md) {
				width: 100%;
			}
			@extend .btn, .btn-outline-dark;
		}
	}
}
`

_Contact Form 7_
`//
// Forms
//
select,
textarea {
	width: 100%;
}
.form-control {
	box-sizing: border-box;
}
.form-group {
	margin-bottom: 20px;
	> label {
		font-size: 0.630rem;
		margin-bottom: 0;
		display: block;
	}
	.form-control {
		&:focus {
			outline: none;
			box-shadow: none;
		}
	}
}
input[type="submit"],
input[type="reset"],
button {
	@extend .btn;
	@extend .btn-primary;
}
.form-text {
	font-weight: 400;
	line-height: 1.4;
	opacity: .65;
}
input {
	&:not([type="submit"]) {
		&:not([type="reset"]) {
			&:not([type="button"]) {
				&:not([type="hidden"]) {
					&:not([type="radio"]) {
						&:not([type="checkbox"]) {
							&:not([type="range"]) {
								@extend .form-control;
							}
						}
					}
				}
			}
		}
	}
}
.wpcf7-form-control {
	&:not(.wpcf7-checkbox) {
		&:not(.wpcf7-radio) {
			&:not(.wpcf7-submit) {
				@extend .form-control;
			}
		}
	}
}
.select2.select2-container--default .select2-selection--single {
	@extend .form-control;
}
// Validação
.wpcf7-not-valid {
	border: 2px solid red;
}
.wpcf7-not-valid-tip {
    color: red;
    font-size: 1em;
    font-weight: normal;
    display: block;
    padding: 0 5px;
    width: max-content;
}
// Checkout
.woocommerce-input-wrapper {
	@extend .form-group;
}`

**Comment by anyssa** [comment]
Since there is a considerable amount of styles that may add to the size of the file, let's keep these as Gists here on GitHub.

**Comment by allysonsouza** [comment]
I think it can be files not imported by default, or commented, to be easily "activated" if needed.
