### ISSUE TITLE
Single: use IDs instead classes for the key layout elements 

### ISSUE THREAD

**Issue by anyssa** [HasteDesign/Haste-Starter#32]
The theme currently uses classes like `.entry-content`, `.entry-header`, `.entry-footer` etc to identify the post sections, both in the archives and the single templates.

In order to diferentiate both contexts, I suggets we use IDs instead classes for these elements in the singular pages. 

We already have elements like THE Header (`#header`), THE Footer (`#footer`) in a more global context (relative to the whole site), so this makes sense since the whole point of the `single.php` template is to display a single entry, therefore, a single entry content, header and footer. 

This will help us to select and style the elements more easily in each context.

**Comment by GabrielHenriqueRS** [comment]
Implementing this idea I think of another alternative, which would be to use a more specific id like # single-header for more used elements and more general classes like .single-header-context.
