### ISSUE TITLE
Ensure text remains visible during webfont load

### ISSUE THREAD

**Issue by allysonsouza** [HasteDesign/Haste-Starter#50]
Take a look at this performance point and see how we can add it as a default attribute for webfonts loaded in the theme:
https://web.dev/font-display/

**Comment by GabrielHenriqueRS** [comment]
Currently, the Haste Starter avoid FOIT and already uses the `font-display: swap;` in file [`src/scss/settings/_fonts.scss`](https://github.com/HasteDesign/Haste-Starter/blob/ad355fe29a94cabfbca2cabcd38b74f87ad97112/src/scss/settings/_fonts.scss#L9)

**Comment by allysonsouza** [comment]
So we can close this issue @GabrielHenriqueRS?

**Comment by GabrielHenriqueRS** [comment]
> 
> 
> So we can close this issue @GabrielHenriqueRS?

Yes, I will close now.
