### ISSUE TITLE
Fix "method_lines" issue in inc/theme-support.php

### ISSUE THREAD

**Issue by allysonsouza** [HasteDesign/Haste-Starter#58]
Method `haste_starter_gutenberg_support` has 55 lines of code (exceeds 25 allowed). Consider refactoring.

https://codeclimate.com/github/HasteDesign/Haste-Starter/inc/theme-support.php#issue_605e4f1f24706d0001000075

**Comment by yankairalla** [comment]
Com a modificação dos suportes para o theme.json essa issue se extinguiu
