### ISSUE TITLE
Remove specific templates and other files

### ISSUE THREAD

**Issue by allysonsouza** [HasteDesign/Haste-Starter#64]
Remove too much specific templates that are not used for most projects and add cognitive complexity to understand the theme structure. Remove files that are not more needed by the project.

### Templates
- [x] `image.php`
- [x] `tag.php`

### Other
- [x] `postcss.config.js` - Check if we still need it

**Comment by yankairalla** [comment]
Não encontrei esse arquivo `image.php`, acredito que já tenha sido deletado.
