### ISSUE TITLE
Remove the content width classes from the <main> tag

### ISSUE THREAD

**Issue by anyssa** [HasteDesign/Haste-Starter#9]
The content width classes should not be defined on the main tag, as it does not allow any div inside it to be full width.

Instead, we should either create the container, row and columns manually or create template tags that generate this structure + sidebar when necessary.

**Comment by anyssa** [comment]
Reopening because there are still some classes remaining, like here for example:

https://github.com/HasteDesign/Haste-Starter/blob/95c4df64774b8ce8bb109c7fa6da0034819b5785/single.php#L12

https://github.com/HasteDesign/Haste-Starter/blob/95c4df64774b8ce8bb109c7fa6da0034819b5785/search.php#L12

https://github.com/HasteDesign/Haste-Starter/blob/95c4df64774b8ce8bb109c7fa6da0034819b5785/tag.php#L12

**Comment by GabrielHenriqueRS** [comment]
Closes: [#e96b68cd](https://github.com/HasteDesign/Haste-Starter/commit/e96b68cde4057aa9955254efeb90d521284b4cb2)
